/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChiselImage: typeof import('./src/components/chisel-image.vue')['default']
    EditBlock: typeof import('./src/components/edit/edit-block.vue')['default']
    EditConfig: typeof import('./src/components/edit/edit-config.vue')['default']
    EditHeader: typeof import('./src/components/edit/edit-header.vue')['default']
    EditRender: typeof import('./src/components/edit/edit-render.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Image: typeof import('./src/components/image/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VIcon: typeof import('./src/components/base/v-icon.vue')['default']
    VIconTooltip: typeof import('./src/components/base/v-icon-tooltip.vue')['default']
    VSelect: typeof import('./src/components/base/v-select.vue')['default']
  }
}
